---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./config:/config
      - /mnt/EXOS18_Anime1/Media/Anime1:/Anime1
      - /mnt/EXOS18_Anime2/Media/Anime2:/Anime2
      - /mnt/EXOS16_TV1/Media/TV1:/TV1 
      - /mnt/EXOS20_TV2/Media/TV2:/TV2
      - /home/jhn/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
