---
version: "3.7"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - WEBUI_PORT=8100
    volumes:
      - ./config:/config
      - /home/jhn/Downloads:/downloads
    ports:
      - 8100:8100
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
