---
version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr-remux
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./config:/config
      - /home/jhn/Docker/containers/Bazarr/config/subcleaner:/subcleaner
      - /mnt/RED06_Remux/Media/Remux:/remux-movies
    ports:
      - 6768:6767
    restart: unless-stopped
