---
version: "2.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./config:/config
      - /home/jhn/Media Addons/Audiobooks:/Audiobooks
      - /home/jhn/Downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
