version: "3.8"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    environment:
      - TZ=Europe/Stockholm
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - nodeName=Sonic
    volumes:
      - /home/jhn/Docker/containers/Tdarr/Server:/app/server
      - /home/jhn/Docker/containers/Tdarr/Server/configs:/app/configs
      - /home/jhn/Docker/containers/Tdarr/Server/logs:/app/logs
      - /home/jhn/Docker/containers/Tdarr/Node/transcode_cache:/temp
      - /home/jhn/Media Addons/Videos:/videos
      - /mnt/RED10_Movies1/Media/Movies1:/movies1
      - /mnt/RED10_Movies2/Media/Movies2:/movies2
      - /mnt/EXOS16_Movies3/Media/Movies3:/movies3
      - /mnt/EXOS18_Anime1/Media/Anime1:/anime1
      - /mnt/EXOS18_Anime2/Media/Anime2:/anime2
      - /mnt/EXOS16_TV1/Media/TV1:/TV1
      - /mnt/EXOS20_TV2/Media/TV2:/TV2

  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      - TZ=Europe/Stockholm
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - nodeName=Tails
      - serverIP=0.0.0.0
      - serverPort=8266
      - inContainer=true
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./config:/config
      - /home/jhn/Docker/containers/Tdarr/Server/logs:/app/logs
      - /home/jhn/Docker/containers/Tdarr/Node/transcode_cache:/temp
      - /home/jhn/Media Addons/Videos:/videos
      - /mnt/RED10_Movies1/Media/Movies1:/movies1
      - /mnt/RED10_Movies2/Media/Movies2:/movies2
      - /mnt/EXOS16_Movies3/Media/Movies3:/movies3
      - /mnt/EXOS18_Anime1/Media/Anime1:/anime1
      - /mnt/EXOS18_Anime2/Media/Anime2:/anime2
      - /mnt/EXOS16_TV1/Media/TV1:/TV1
      - /mnt/EXOS20_TV2/Media/TV2:/TV2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
