version: "3"
services:
  watchtower:
    container_name: watchtower
    restart: unless-stopped
    environment:
      WATCHTOWER_SCHEDULE: 0 0 7 * * MON
      TZ: Europe/Stockholm
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
