version: "2.1"
services:
  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:develop
    container_name: plex-meta-manager-run
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - PMM_DELETE_LABELS=true
      - PMM_CONFIG=/config/config.yml #optional
      - PMM_RUN=True #optional
      - PMM_TEST=False #optional
      - PMM_NO_MISSING=False #optional
    volumes:
      - ./config:/config
    restart: unless-stopped

 
#cd /home/jhn/Docker/containers/Plex-meta-manager
#sudo docker-compose up -d

#docker pull meisnate12/plex-meta-manager
#sudo docker-compose up -d
