---
version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./config:/config
      - /home/jhn/Docker/containers/Bazarr/config/subcleaner:/subcleaner
      - /mnt/RED10_Movies1/Media/Movies1:/movies1
      - /mnt/RED10_Movies2/Media/Movies2:/movies2
      - /mnt/EXOS16_Movies3/Media/Movies3:/movies3
      - /mnt/EXOS18_Anime1/Media/Anime1:/anime1
      - /mnt/EXOS18_Anime2/Media/Anime2:/anime2
      - /mnt/EXOS16_TV1/Media/TV1:/TV1
      - /mnt/EXOS20_TV2/Media/TV2:/TV2
    ports:
      - 6767:6767
    restart: unless-stopped
