version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=Europe/Stockholm
       ports:
            - 5065:5055
       volumes:
            - ./config:/app/config
       restart: unless-stopped
